I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 16, in script call
    call memorial_game_start
  File "game/memorial-game.rpy", line 40, in script
    $ rnezrandom.shuffle(cards)
  File "game/memorial-game.rpy", line 40, in <module>
    $ rnezrandom.shuffle(cards)
NameError: name 'rnezrandom' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 16, in script call
    call memorial_game_start
  File "game/memorial-game.rpy", line 40, in script
    $ rnezrandom.shuffle(cards)
  File "C:\Users\user\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\user\Downloads\renpy-8.2.3-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/memorial-game.rpy", line 40, in <module>
    $ rnezrandom.shuffle(cards)
NameError: name 'rnezrandom' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.2.3.24061702
secret recipe 1.0
Mon Jul 15 18:37:22 2024
